// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Hub is an autogenerated mock type for the Hub type
type Hub struct {
	mock.Mock
}

// NotifyResetRumorSender provides a mock function with given fields:
func (_m *Hub) NotifyResetRumorSender() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NotifyResetRumorSender")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewHub creates a new instance of Hub. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHub(t interface {
	mock.TestingT
	Cleanup(func())
}) *Hub {
	mock := &Hub{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
