// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	mmessage "popstellar/internal/handler/message/mmessage"

	mock "github.com/stretchr/testify/mock"
)

// MessageHandler is an autogenerated mock type for the MessageHandler type
type MessageHandler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: channelPath, msg, fromRumor
func (_m *MessageHandler) Handle(channelPath string, msg mmessage.Message, fromRumor bool) error {
	ret := _m.Called(channelPath, msg, fromRumor)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, mmessage.Message, bool) error); ok {
		r0 = rf(channelPath, msg, fromRumor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMessageHandler creates a new instance of MessageHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageHandler {
	mock := &MessageHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
