// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Sockets is an autogenerated mock type for the Sockets type
type Sockets struct {
	mock.Mock
}

// SendToRandom provides a mock function with given fields: buf
func (_m *Sockets) SendToRandom(buf []byte) {
	_m.Called(buf)
}

// NewSockets creates a new instance of Sockets. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSockets(t interface {
	mock.TestingT
	Cleanup(func())
}) *Sockets {
	mock := &Sockets{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
