// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	message "popstellar/internal/message/mmessage"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// HasMessage provides a mock function with given fields: messageID
func (_m *Repository) HasMessage(messageID string) (bool, error) {
	ret := _m.Called(messageID)

	if len(ret) == 0 {
		panic("no return value specified for HasMessage")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(messageID)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(messageID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(messageID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreChirpMessages provides a mock function with given fields: channel, generalChannel, msg, generalMsg
func (_m *Repository) StoreChirpMessages(channel string, generalChannel string, msg message.Message, generalMsg message.Message) error {
	ret := _m.Called(channel, generalChannel, msg, generalMsg)

	if len(ret) == 0 {
		panic("no return value specified for StoreChirpMessages")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, message.Message, message.Message) error); ok {
		r0 = rf(channel, generalChannel, msg, generalMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
