// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	socket "popstellar/internal/network/socket"

	mock "github.com/stretchr/testify/mock"
)

// RumorStateSender is an autogenerated mock type for the RumorStateSender type
type RumorStateSender struct {
	mock.Mock
}

// SendRumorStateTo provides a mock function with given fields: _a0
func (_m *RumorStateSender) SendRumorStateTo(_a0 socket.Socket) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SendRumorStateTo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(socket.Socket) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRumorStateSender creates a new instance of RumorStateSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRumorStateSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *RumorStateSender {
	mock := &RumorStateSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
