// fake events to show how the app works
import { LaoEventState, LaoEventType } from 'model/objects';

// @ts-ignore
const data: LaoEventState[] = [
  {
    id: '1',
    eventType: LaoEventType.MEETING,
    name: 'Events 1',
    creation: 1607616483,
    last_modified: 1607616483,
    location: 'A location, test.com',
    start: 1607616500,
    end: 1607618490,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    id: '2',
    eventType: LaoEventType.MEETING,
    name: 'Events 2',
    creation: 1607616483,
    last_modified: 1607616483,
    location: 'A location, test.com',
    start: 1607616483,
    end: 1607618490,
    organizer: 'i7NMjdW2tkBj4uMCM15rlckmQCdR0anffOTD+MQg3XQ=',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    id: '3',
    eventType: LaoEventType.MEETING,
    name: 'Events 3',
    creation: 1607616483,
    last_modified: 1607616483,
    location: 'A location, test.com',
    start: 1607616483,
    end: 1607618490,
    organizer: 'a organizer signature',
    witnesses: ['i7NMjdW2tkBj4uMCM15rlckmQCdR0anffOTD+MQg3XQ=', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{
      witness: 'Witness 1',
      signature: 'witness signature 1',
    }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    id: '4',
    eventType: LaoEventType.ROLL_CALL,
    name: 'Events 4',
    creation: 1607616483,
    last_modified: 1607616483,
    start: 1607616483,
    end: 1607618490,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{
      witness: 'Witness 1',
      signature: 'witness signature 1',
    }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    id: '5',
    eventType: LaoEventType.ROLL_CALL,
    name: 'Events 5',
    creation: 1607616483,
    last_modified: 1607616483,
    start: 1607616483,
    end: 1607618490,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    id: '6',
    eventType: LaoEventType.MEETING,
    name: 'Events 6',
    creation: 1607616483,
    last_modified: 1607616483,
    start: 1607616483,
    end: 1607618490,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    id: '7',
    eventType: LaoEventType.MEETING,
    name: 'Events 7',
    creation: 1607616483,
    last_modified: 1607616483,
    location: 'A location, test.com',
    start: 1607616483,
    end: 1607618490,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    id: '8',
    eventType: LaoEventType.MEETING,
    name: 'Events 8',
    creation: 1607616483,
    last_modified: 1607616483,
    location: 'A location, test.com',
    start: 1607616483,
    end: 1607618490,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    id: '9',
    eventType: LaoEventType.MEETING,
    name: 'Events 9',
    creation: 1607616483,
    last_modified: 1607616483,
    location: 'A location, test.com',
    start: 1607616483,
    end: 1607618490,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    id: '10',
    eventType: LaoEventType.MEETING,
    name: 'Events 10',
    creation: 1607616483,
    last_modified: 1607616483,
    location: 'A location, test.com',
    start: 1607616483,
    end: 1607618490,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    id: '11',
    eventType: LaoEventType.ROLL_CALL,
    name: 'Events 11',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    id: '12',
    eventType: LaoEventType.MEETING,
    name: 'Events 12',
    creation: 1607616483,
    last_modified: 1607616483,
    location: 'A location, test.com',
    start: 1607616483,
    end: 1607618490,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    id: '13',
    eventType: LaoEventType.MEETING,
    name: 'Events 13',
    creation: 1607616483,
    last_modified: 1607616483,
    location: 'A location, test.com',
    start: 1607616483,
    end: 1607618490,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    id: '14',
    eventType: LaoEventType.MEETING,
    name: 'Events 14',
    creation: 1607616483,
    last_modified: 1607616483,
    location: 'A location, test.com',
    start: 1607616483,
    end: 1607618490,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    id: '15',
    eventType: LaoEventType.MEETING,
    name: 'Events 15',
    creation: 1607616483,
    last_modified: 1607616483,
    location: 'A location, test.com',
    start: 1607616483,
    end: 1607618490,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    id: '16',
    eventType: LaoEventType.MEETING,
    name: 'Events 16',
    creation: 1607616483,
    last_modified: 1607616483,
    location: 'A location, test.com',
    start: 1607616483,
    end: 1607618490,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    id: '17',
    eventType: LaoEventType.MEETING,
    name: 'Events 17',
    creation: 1607616483,
    last_modified: 1607616483,
    location: 'A location, test.com',
    start: 1607616483,
    end: 1607618490,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    id: '18',
    eventType: LaoEventType.MEETING,
    name: 'Events 18',
    creation: 1607616483,
    last_modified: 1607616483,
    location: 'A location, test.com',
    start: 1607616483,
    end: 1607618490,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    id: '19',
    eventType: LaoEventType.MEETING,
    name: 'Events 19',
    creation: 1607616483,
    last_modified: 1607616483,
    location: 'A location, test.com',
    start: 1607616483,
    end: 1607618490,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    id: '20',
    eventType: LaoEventType.MEETING,
    name: 'Events 20',
    creation: 1607616483,
    last_modified: 1607616483,
    location: 'A location, test.com',
    start: 1607616483,
    end: 1607618490,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
];

// Sort (ascending) by start, then by end
const sorted = data.sort((a, b) => {
  if (a.start < b.start) {
    return -1;
  }

  if (a.start === b.start) {
    if (a.end < b.end) {
      return -1;
    }
    if (a.end === b.end) {
      return 0;
    }
  }

  return 1;
});

export default sorted;
