// fake LAOsto to show how the app works
const data = [
  {
    object: 'lao',
    action: 'state',
    id: '31',
    name: 'LAO 1',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '32',
    name: 'LAO 2',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'i7NMjdW2tkBj4uMCM15rlckmQCdR0anffOTD+MQg3XQ=',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '33',
    name: 'LAO 3',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['i7NMjdW2tkBj4uMCM15rlckmQCdR0anffOTD+MQg3XQ=', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '34',
    name: 'LAO 4',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '35',
    name: 'LAO 5',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '36',
    name: 'LAO 6',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '37',
    name: 'LAO 7',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '38',
    name: 'LAO 8',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '39',
    name: 'LAO 9',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '310',
    name: 'LAO 10',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '311',
    name: 'LAO 11',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '312',
    name: 'LAO 12',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '313',
    name: 'LAO 13',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '314',
    name: 'LAO 14',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '315',
    name: 'LAO 15',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '316',
    name: 'LAO 16',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '317',
    name: 'LAO 17',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '318',
    name: 'LAO 18',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '319',
    name: 'LAO 19',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '320',
    name: 'LAO 20',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
];

export default data;
