// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"popstellar/internal/message/method/mgetmessagesbyid"
)

// Queries is an autogenerated mock type for the Queries type
type Queries struct {
	mock.Mock
}

// AddQuery provides a mock function with given fields: ID, query
func (_m *Queries) AddQuery(ID int, query mgetmessagesbyid.GetMessagesById) {
	_m.Called(ID, query)
}

// GetNextID provides a mock function with given fields:
func (_m *Queries) GetNextID() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNextID")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// NewQueries creates a new instance of Queries. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueries(t interface {
	mock.TestingT
	Cleanup(func())
}) *Queries {
	mock := &Queries{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
