// fake LAOsto to show how the app works
const data = [
  {
    object: 'lao',
    action: 'state',
    id: '1',
    name: 'LAO 1',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '2',
    name: 'LAO 2',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '3',
    name: 'LAO 3',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '4',
    name: 'LAO 4',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '5',
    name: 'LAO 5',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '6',
    name: 'LAO 6',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '7',
    name: 'LAO 7',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '8',
    name: 'LAO 8',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '9',
    name: 'LAO 9',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '10',
    name: 'LAO 10',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '11',
    name: 'LAO 11',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '12',
    name: 'LAO 12',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '13',
    name: 'LAO 13',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '14',
    name: 'LAO 14',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '15',
    name: 'LAO 15',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '16',
    name: 'LAO 16',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '17',
    name: 'LAO 17',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '18',
    name: 'LAO 18',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '19',
    name: 'LAO 19',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
  {
    object: 'lao',
    action: 'state',
    id: '20',
    name: 'LAO 20',
    creation: 1607616483,
    last_modified: 1607616483,
    organizer: 'a organizer signature',
    witnesses: ['witness signature 1', 'witness signature 2'],
    modification_id: 'a modification id',
    modification_signatures: [{ witness: 'Witness 1', signature: 'witness signature 1' }, { witness: 'Witness 2', signature: 'witness signature 2' }],
  },
];

export default data;
