name: PoP CI fe1-web

on:
  push:
    branches: [ work-fe1-* ]
  pull_request:
    branches: [ fe1-web ]

jobs:
  build:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: expo/expo-github-action@v5
      with:
        expo-version: 4.x
    - name: Cache Node Modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-   
          ${{ runner.os }}-build- 
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        cd fe1-web
        npm install
        npm audit fix
    - name: expo doctor
      run: |
        cd fe1-web
        expo doctor
    - name: Build project
      run: |
        cd fe1-web
        expo build:web

  testAndLint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Cache Node Modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-   
          ${{ runner.os }}-build- 
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        cd fe1-web
        npm install
        npm audit fix
    - name: Run lint
      run: |
        cd fe1-web
        npm run eslint --if-present
    - name: Run test
      run: |
        cd fe1-web
        npm run test --if-present
